{% set name = "targ" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Upstream did a wacky rebuild with '-1' in the version here, make sure to remove
  url: https://github.com/piccolo-orm/targ/archive/{{ version }}-1.tar.gz
  sha256: 0ed6ab283004156e15fab22c97c5cd65faa2cf16a98c2b4977b157432fe03a38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - colorama ==0.4.*
    - docstring_parser >=0.12
  run:
    - python >=3.8
    - colorama ==0.4.*
    - docstring_parser >=0.12

test:
  imports:
    - targ
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/piccolo-orm/targ/
  doc_url: https://targ.readthedocs.io/en/latest/index.html
  summary: Build a Python CLI for your app, just using type hints and docstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
